server.port=8080
spring.thymeleaf.cache=false
camunda.client.prefer-rest-over-grpc=false

camunda.client.cloud.cluster-id=${ZB_CLUSTER}
camunda.client.auth.client-id=${ZB_CLIENT}
camunda.client.auth.client-secret=${ZB_SECRET}
camunda.client.cloud.region=${ZB_REGION:fra-1}

logging.level.io.camunda.client.impl.CamundaCallCredentials=ERROR